### ISSUE TITLE
Sanely handle the new ggml weights against the old llama weights distributed by nomic

### ISSUE THREAD

**Issue by bmschmidt** [nomic-ai/pyllamacpp#1]
We have two different quantized formats floating around. The `nomic` package downloads the old-style quantized weights--this package consumes the new weights instead.

We were storing weights in `~/.nomic`, and `pyllamacpp` stores in `~/.models`. The sanest thing to my mind is to use `~/.models` to store new-style weights and `~/.nomic` for the old ones. I think this will cause the least confusion overall, but I'm open to any other proposals.

The other issue is conversion and distribution of the new-style weights for GPT4All models. There's no reason to make people do this conversion on the cli. We should:

[ ] Distribute new-style weights suitable to be auto-download into `~/.models` through the nomic channels (i.e., the Eye).
[ ] Look into whether it's kosher to distribute the llama tokenizer files currently referenced as `path/to/llama_tokenizer`. I really think that this should be OK--it's just a list of tokens, right?

**Comment by abdeladim-s** [comment]
Yes I agree @bmschmidt, 

* It is better to convert and distribute the converted gpt4all weights, so it will be ready to be consumed by `pyllamacpp`. But I think it is better to keep them in the gp4all repo. (btw `pyllamacpp` does no store any weights, there is no `~/.models` folder, users need to provide the path to their models).    

* Basically, it is just  a list of tokens :laughing: , but who knows with this new `AI` laws!

**Comment by bmschmidt** [comment]
Yeah agreed. I don't think the actual weights will go in any repo--but I might want to adopt some of the standards we were groping towards from the `nomic` repo for where these things should live and auto-downloading. My thinking is that basically we have old-style and new-style versions of `gpt4all-lora-quantized.bin` etc. My understanding is that the new-style ones load significantly faster. (Haven't had time to benchmark myself.) So we just need to namespace them somehow for people who already downloaded the old ones.

**Comment by abdeladim-s** [comment]
Yeah, I see. 
It is a good idea to auto-download the models and use the bindings out of the box, without extra downloading and converting overhead. 
The new format is loading almost instantly, compared to the old ones. 
I think we just need to drop the old ones, and make a direct link to the new converted ones. and implement the auo-downloading feature and storing the models somewhere like `~/user_folder/pyllamacpp/models`

**Comment by AndriyMulyar** [comment]
A link to converted ggML weights are being distributed soon

**Comment by AndriyMulyar** [comment]
gpt4all converted (for future travelers): https://the-eye.eu/public/AI/models/nomic-ai/gpt4all/gpt4all-lora-quantized-ggml.bin
