### ISSUE TITLE
OOM using gpt4all model (code 137, SIGKILL)

### ISSUE THREAD

**Issue by MLTQ** [nomic-ai/pyllamacpp#12]
Just running the quickstart code, I'm getting a:

`Process finished with exit code 137 (interrupted by signal 9: SIGKILL)`

after only a few tokens of output, which is generally thrown when a process is consuming too much memory in my experience. 

This is strange because I can run the 30B llamacpp model just fine (m1 32G MBP). 

```
llama_model_load: loading model from './models/gpt4all-unc.ggml' - please wait ...
llama_model_load: n_vocab = 32001
llama_model_load: n_ctx   = 512
llama_model_load: n_embd  = 4096
llama_model_load: n_mult  = 256
llama_model_load: n_head  = 32
llama_model_load: n_layer = 32
llama_model_load: n_rot   = 128
llama_model_load: f16     = 2
llama_model_load: n_ff    = 11008
llama_model_load: n_parts = 1
llama_model_load: type    = 1
llama_model_load: ggml map size = 4017.70 MB
llama_model_load: ggml ctx size =  81.25 KB
llama_model_load: mem required  = 5809.78 MB (+ 2052.00 MB per state)
llama_model_load: loading tensors from './models/gpt4all-unc.ggml'
llama_model_load: model size =  4017.27 MB / num tensors = 291
llama_init_from_file: kv self size  =  512.00 MB
llama_generate: seed = 1680585483

system_info: n_threads = 4 / 10 | AVX = 0 | AVX2 = 0 | AVX512 = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | VSX = 0 | 
sampling: temp = 0.800000, top_k = 40, top_p = 0.950000, repeat_last_n = 64, repeat_penalty = 1.100000
generate: n_ctx = 512, n_batch = 8, n_predict = 55, n_keep = 0



llama_print_timings:        load time =   830.96 ms
llama_print_timings:      sample time =    39.37 ms /    55 runs   (    0.72 ms per run)
llama_print_timings: prompt eval time =   614.90 ms /     7 tokens (   87.84 ms per token)
llama_print_timings:        eval time =  4340.80 ms /    54 runs   (   80.39 ms per run)
llama_print_timings:       total time =  5211.85 ms
 Once upon a time, 465 people signed up to receive my newsletter.
My newsletter has been around for quite some time now. I'm sure that many of the original subscribers have either moved on or lost interest in it over the years, but I still like to think

Process finished with exit code 137 (interrupted by signal 9: SIGKILL)


```

**Comment by itachiluan** [comment]
Yep, I got something similar:
```
llama_print_timings:        load time =  5095.30 ms
llama_print_timings:      sample time =    71.48 ms /   100 runs   (    0.71 ms per run)
llama_print_timings: prompt eval time =  4513.06 ms /     7 tokens (  644.72 ms per token)
llama_print_timings:        eval time =  9736.47 ms /    99 runs   (   98.35 ms per run)
llama_print_timings:       total time = 14906.82 ms
Python(8243,0x1f894c140) malloc: *** error for object 0x3cb1b4000: pointer being freed was not allocated
Python(8243,0x1f894c140) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    8243 abort      python3 main.py
```

**Comment by abdeladim-s** [comment]
@MLTQ, @itachiluan,  could you please let me know what parameters are you using ?

**Comment by namp** [comment]
This is the output I'm getting with [itachiluan]'s code above:

llama_model_load: loading model from './models/gpt4all-converted.bin' - please wait ...
llama_model_load: n_vocab = 32001
llama_model_load: n_ctx   = 512
llama_model_load: n_embd  = 4096
llama_model_load: n_mult  = 256
llama_model_load: n_head  = 32
llama_model_load: n_layer = 32
llama_model_load: n_rot   = 128
llama_model_load: f16     = 2
llama_model_load: n_ff    = 11008
llama_model_load: n_parts = 1
llama_model_load: type    = 1
llama_model_load: ggml map size = 4017.70 MB
llama_model_load: ggml ctx size =  81.25 KB
llama_model_load: mem required  = 5809.78 MB (+ 2052.00 MB per state)
llama_model_load: loading tensors from './models/gpt4all-converted.bin'
llama_model_load: model size =  4017.27 MB / num tensors = 291
llama_init_from_file: kv self size  =  512.00 MB
llama_generate: seed = 1680611369

system_info: n_threads = 4 / 48 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
sampling: temp = 0.800000, top_k = 40, top_p = 0.950000, repeat_last_n = 64, repeat_penalty = 1.100000
generate: n_ctx = 512, n_batch = 8, n_predict = 100, n_keep = 0


 Once upon a time, 26 people attended the meeting. Now there are only 25 attendees. How many more people would have been attending if all possible attendees had attended? [end of text]

llama_print_timings:        load time =  3614.07 ms
llama_print_timings:      sample time =    35.62 ms /    39 runs   (    0.91 ms per run)
llama_print_timings: prompt eval time =  1967.40 ms /     7 tokens (  281.06 ms per token)
llama_print_timings:        eval time = 13340.02 ms /    38 runs   (  351.05 ms per run)
llama_print_timings:       total time = 16991.29 ms
**Segmentation fault**

**Comment by abdeladim-s** [comment]
Please update the package to the latest version `1.0.6` 
```shell
pip install pyllamacpp --upgrade
```
Let me know if the issue is solved ?

**Comment by itachiluan** [comment]
Worked for me! Thanks!

**Comment by MLTQ** [comment]
This solved it!
