### ISSUE TITLE
invalid model file (bad magic [got 0x67676d66 want 0x67676a74])

### ISSUE THREAD

**Issue by nocpinmylf** [nomic-ai/pyllamacpp#17]
This happen when i try to run the model with tutor in Readme.md

my code:
```
from pyllamacpp.model import Model

def new_text_callback(text: str):
    print(text, end="")


if __name__ == "__main__":
  prompt = "Once upon a time, "
  model = Model(ggml_model='chat\gpt4all-lora-unfiltered-quantized-ggml.bin', n_ctx=512)
  model.generate(prompt, n_predict=55, new_text_callback=new_text_callback, n_threads=8)
```

`
chat\gpt4all-lora-unfiltered-quantized-ggml.bin: invalid model file (bad magic [got 0x67676d66 want 0x67676a74])
        you most likely need to regenerate your ggml files
        the benefit is you'll get 10-100x faster load times
        see https://github.com/ggerganov/llama.cpp/issues/91
        use convert-pth-to-ggml.py to regenerate from original pth
        use migrate-ggml-2023-03-30-pr613.py if you deleted originals
llama_init_from_file: failed to load model
llama_generate: seed = 1680611669
`

**Comment by DeadRedmond** [comment]
although it is written here that a ggml model is needed, but in fact now llama.cpp uses the ggjt model

**Comment by abdeladim-s** [comment]
Yes, as @DeadRedmond said, `llama.cpp` is now using a `ggjt` model format.
You will need to convert the model to the new format using the provided script.

We will change the `param` name in the future release.

**Comment by VincentWang25** [comment]
Could you please elaborate more on how to convert ggml to ggjt format?

**Comment by abdeladim-s** [comment]
@VincentWang25 Please try [this](https://github.com/ggerganov/llama.cpp/issues/662#issuecomment-1492712443)

**Comment by VincentWang25** [comment]
Thank you. It works like charm :)
