### ISSUE TITLE
Are embeddings planned?

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [nomic-ai/pyllamacpp#20]
Hi,

just wanted to know if it was planned for these bindings to provide embeddings from strings

Thanks!

**Comment by bmschmidt** [comment]
Yes, step 1 on this will be https://github.com/nomic-ai/pyllamacpp/issues/3. Note that these will be weights intended to predict token-level descriptions, so it won't be a drop-in replacement for a good sentence-level embedding model--but doing so is an interesting research project!
