### ISSUE TITLE
symbol not found in flat namespace '_cblas_sgemm'

### ISSUE THREAD

**Issue by aribo** [nomic-ai/pyllamacpp#36]
I get this error when trying to import Model 
`from pyllamacpp.model import Model`

It's on MacOS M1, python 3.10.10

**Comment by itnoobzzy** [comment]
![image](https://user-images.githubusercontent.com/52363409/230350250-e422c8d5-860b-4d4a-9818-3ae764a44162.png)
first step, get common error

**Comment by nuance1979** [comment]
Same here. macOS with M1 Pro chip.

**Comment by bluebenzene** [comment]
same here with macos intel chip . bigsur

**Comment by abdeladim-s** [comment]
I have merged @nuance1979 PR, 
@aribo, @bluebenzene Could you please give it a try now?

**Comment by aribo** [comment]
It works for me 👍🏼

**Comment by abdeladim-s** [comment]
Prefect. 
Thanks again @nuance1979.
