### ISSUE TITLE
Suggestions for running on windows?

### ISSUE THREAD

**Issue by timwillhack** [nomic-ai/pyllamacpp#38]
Running into errors when installing wheels

**Comment by abdeladim-s** [comment]
@timwillhack, what errors ?

**Comment by timwillhack** [comment]
sentencepiece_wrap.cxx
      src/sentencepiece/sentencepiece_wrap.cxx(2822): fatal error C1083: Cannot open include file: 'sentencepiece_processor.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

**Comment by abdeladim-s** [comment]
you are having problems installing [sentencepiece](https://github.com/google/sentencepiece).
Please take a look at their repo and report the issue there

**Comment by AlbelTec** [comment]
I wonder if you are running python 3.11 : if so there no sentencepiece package for this version. you need to downgrade to 3.10

**Comment by markusantonuis** [comment]
there is now, I have it installed on 3.11
