### ISSUE TITLE
Error running quickstart code - AttributeError: 'Model' object has no attribute '_ctx'`

### ISSUE THREAD

**Issue by MLTQ** [nomic-ai/pyllamacpp#8]
# Problem:
```
AttributeError: '_pyllamacpp.llama_context_params' object has no attribute 'n_threads'

Exception ignored in: <function Model.__del__ at 0x103092940>

Traceback (most recent call last):

  File ".../lib/python3.9/site-packages/pyllamacpp/model.py", line 136, in __del__

    pp.llama_free(self._ctx)

AttributeError: 'Model' object has no attribute '_ctx'
```

# Steps to reproduce:
pip install pyllamacpp
Download gpt4all model from linked github page, 
~Convert using llamma.cpp's convert-gpt4all-to-ggml.py script~
Convert using pyllamacpp-convert-gpt4all
Run quick start code

~As of current revision, there is no `pyllamacpp-convert-gpt4all` script or function after install, so I suspect what is happening that that the model isn't in the right format. Where is the right conversion script?~

edit: whoops, I had the wrong environment set up. Using the correct `pyllamacpp-convert-gpt4all` to convert the model results in the same exact error

**Comment by itachiluan** [comment]
I did find the `pyllamacpp-convert-gpt4all` after installing `pyllamacpp`, but after the model is converted, the same error still comes up

**Comment by abdeladim-s** [comment]
Thanks @MLTQ, @itachiluan for pointing that out. 
The `n_threads` param should be passed to the generate function. 

I will update the readme as well as the documentation very soon.

**Comment by MLTQ** [comment]
Yep! That solved it!
